spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baseframework?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wahwk123123.
    driver-class-name: com.mysql.cj.jdbc.Driver
